### ISSUE TITLE
Error in index.json  , a extra square bracket is there after id : 196

### ISSUE THREAD

**Issue by AhzamAkhtar** [gdscwce/Indian-Landmarks-API-#163]
![problem](https://user-images.githubusercontent.com/94620460/193403361-307286a4-4b18-4cd5-a6c9-2ed664b13622.png)

**Comment by AhzamAkhtar** [comment]
i have raised a pull request in which i have solved this issue and added new landmark.

**Comment by yogesh-9999** [comment]
hey @AhzamAkhtar  assign me this issue

**Comment by AhzamAkhtar** [comment]
@yogesh-9999 this issue has been resolved
